path:
  root_dir: /root/task5_2023
  # root_dir: /d/individual_project/task5_2023
  data_dir: ${path.root_dir}/Data_Set
  train_dir: ${path.data_dir}/Training_Set
  val_dir: ${path.data_dir}/Validation_Set
  test_dir: ${path.data_dir}/Evaluation_Set
  pretrain_dir: ${path.data_dir}/WMW
  feature_dir: ${path.root_dir}/Features
  train_feature_dir: ${path.feature_dir}/Training_Set
  val_feature_dir: ${path.feature_dir}/Validation_Set
  test_feature_dir: ${path.feature_dir}/Validation_Set
  pretrain_feature_dir: ${path.feature_dir}/WMW
  

features:
  sr: 22050
  n_mels: 128
  n_fft: 1024
  hop_length: 256
  win_length: ${features.n_fft}
  fmin: 50
  fmax: 11025
  feature_list: pcen #&logmel&pcen&mfcc
  segment_length: 0.2
  segment_len_frame: 17
  inchannel: 8


train:
  neg_prototype: False
  n_way: 10
  n_support: 5
  n_query: 5
  # backbone:  convclassifierfw
  # backbone:  convnetfwlarge
  backbone:  convnet
  model_type: protonet
  epoches: 51
  lr: 0.001
  lr_inner: 0.01
  momentum: 0.9
  weight_decay: 0.0005
  optimizer: Adam
  task_batch_size: 20
  inner_step: 5
  min_lr: 0.001
  multi_step_loss_num_epochs: 15
  first_order_to_second_order_epoch: 15
  enable_inner_loop_optimizable_bn_params: False
  second_order: false
  use_multi_step_loss_optimization: False
  learnable_bn_gamma: True
  learnable_bn_beta: True
  per_step_bn_statistics: True
  norm_layer: batch_norm
  margin: 0.1

val:
  seg_len_base: 30
  hop_len_frac: 3
  test_loop_batch_size: 1024
  test_loop_neg_sample: 50
  threshold: 0.5



checkpoint:
  save_freq: 5
  resume: false
  best_model_dir: ${checkpoint.model_dir}/model_best.pth.tar
  start_epoch: 0
  experiment_name: Trinet${train.backbone}_${version}
  # experiment_name: anchornet
  # experiment_name: protnnet_10way_5shot_res
  # experiment_name: test
  exp_dir: ${path.root_dir}/Checkpoints/${checkpoint.experiment_name}
  model_dir: ${checkpoint.exp_dir}/Model
  pred_dir: ${checkpoint.exp_dir}/Predictions
  report_dir: ${checkpoint.exp_dir}/Reports

team_name: tw1022
dataset: EVAL
#EVAL or VAL
version: _formal_hard1